### ISSUE TITLE
Not Recording with Google Chrome on a PC

### ISSUE THREAD

**Issue by tarekeldeeb** [Tarteel-io/tarteel.io#101]
Congrats for that nice project. I tried it on a smart phone and on a PC.

On PC, IE is not compatible, that's expected with no worries ..
But on Google chrome, it's expected to work. Page loads, and after "Start" is pressed, the Quran verse and the "Mic" icons are show.

When the "Mic" icons is pressed, nothing happens.
- Does not record
- Does not even ask for recording permission

On the JS console, the following are logged with each "Mic" press.

> Audio context set up.
> navigator.getUserMedia available. recorder_object.js:38

**Comment by abidlabs** [comment]
More broadly speaking, we need to systematically check browser/device incompatibility.

**Comment by abidlabs** [comment]
@tarekeldeeb I'm trying to reproduce this issue, but I don't experience it when I use Chrome on a PC. Could you please let me know if you are still experiencing this issue? 

If so, can you check whether you are on: **http** or **https** version of the website? (In general, you should be redirected to **https** but we were at one point seeing this issue with the **http** version of the website)

**Comment by tarekeldeeb** [comment]
@abidlabs Unfortunately, it's consistent. Just as you've mentioned, I'm already on https.

**Comment by bahaa96** [comment]
Sent by GO Mail

**Comment by tarekeldeeb** [comment]
Oops, after a couple of refreshes, window moves, I finally got the permission request from tarteel.io. Once approved, it worked as expected.

So let me redefine the problem now:
The recording permission was not requested as soon as the site loads. Random refresh cycles triggered it.

**Comment by abidlabs** [comment]
Thank you @tarekeldeeb, that's very helpful to know.

**Comment by MohammedEssehemy** [comment]
@tarekeldeeb  I need more details, OS  and chrome version.
