### ISSUE TITLE
Add ability to switch from Arabic text to English transliteration

### ISSUE THREAD

**Issue by abidlabs** [Tarteel-io/tarteel.io#103]
One user commented, "With offering transliteration (or just the option to recite suras and ayat people have memorised), you'd open up the crowdsourcing to far more people. Many Muslims grow up "reading" Arabic so they can recite (especially those who to go Islamic schools), but many Muslims (especially converts) do not have that training from childhood and have learned Qur'an primarily by listening repeatedly to audio recitations. They can very very slowly read Arabic, but cannot sound out the words with any reasonable speed."

Once we implement this, we should also include a field in the "AnnotatedRecordings" table which marks whether the Arabic verse was recited or the English transliteration.

**Comment by piraka9011** [comment]
If no one has this, I can tackle implementation. I'll add a button beside the Ayah to switch.

**Comment by abidlabs** [comment]
That sounds great @Anas, this is all yours!

**Comment by piraka9011** [comment]
I've scraped the data from https://sahih-bukhari.com/Pages/Quran/Quran_transliteration.php into a csv.
Will create a `getTransliteratedAyah` endpoint to minimize data load.

**Comment by abidlabs** [comment]
Thanks @piraka9011!
