### ISSUE TITLE
Change Surah and Ayah page stuck on Firefox

### ISSUE THREAD

**Issue by mmayet** [Tarteel-io/tarteel.io#137]
When I click to change the surah/ayah on firefox, it shows me a static non-scrolling page of verses. I can select the verses shown, but there's no back to surahs, no scroll to view verses, and no search bar at the top either.
![tarteel_mozilla_bug](https://user-images.githubusercontent.com/6694374/49421092-54a88580-f743-11e8-94ac-d320aa952498.png)

**Comment by piraka9011** [comment]
This has been resolved in the new front end
