### ISSUE TITLE
Branch Cleanup

### ISSUE THREAD

**Issue by piraka9011** [Tarteel-io/tarteel.io#138]
The following branches seem stale:
`abdellatif/miscellaneous-fixes`
`og_img_update`
`abdellatif/hotjar`
`develop`
`revert-104-master`
`abdellatif/misc_fixes`
`bahaa/localization`
`bahaa/ajax-queueing`
`bahaa/adding-explanatory-comments `
`bahaa/landscape-issue`
@abidlabs @tifa2UP @bahaa96  Permission to delete?

**Comment by tifa2UP** [comment]
go for it
