### ISSUE TITLE
Create data download page that allows download of full audio dataset

### ISSUE THREAD

**Issue by abidlabs** [Tarteel-io/tarteel.io#139]
Currently, we have a page (https://www.tarteel.io/download-audio), which allows users to download a sample set of 50 recordings and listen to a few audio samples. 

Now that we have reached 10k recordings, we should allow people to download all of the recordings that we have collected. Let's have a link, which allows a user to download a CSV file consists of the following information for each recording:

- URL path to the recording
- Surah number
- Ayah number
- Demographic information of reciter (if available)
- Recitation_mode (if available)
- Timestamp of recording submission
- Whether the recording has been evaluated for hifz (for now, this should always be False).

This may be useful inspiration: http://image-net.org/download

**Comment by piraka9011** [comment]
Basic html page in `audio` app that queries all objects should be simple.
I can grab this after finishing tajweed if no one has it.

**Comment by abidlabs** [comment]
Thanks @piraka9011, @khanh111 has picked it up.

**Comment by abidlabs** [comment]
@
