### ISSUE TITLE
Adding a login feature for users

### ISSUE THREAD

**Issue by piraka9011** [Tarteel-io/tarteel.io#140]
It'd be nice to have a feature where users can login and see the recitations associated with their account. 
It would also make sure only select people access the tajweed evaluation tool in progress.

Currently we have [`django-allauth`](https://django-allauth.readthedocs.io/en/latest/) app taking care of most of this. I've added most backend configs but need to make login page.

**Comment by nightblade9** [comment]
It would also be nice to see a count of ayaat evaluated by a user. I'm not reciting but I am verifying quite a lot.
