### ISSUE TITLE
Waqf signs missing

### ISSUE THREAD

**Issue by abidlabs** [Tarteel-io/tarteel.io#141]
Can we add waqf signs? I got this feedback from a user: "the waqf signs are missing, which affects the recitation tremendously."

![img-20181207-wa0010](https://user-images.githubusercontent.com/1778297/49673942-3fcb3b00-fa3e-11e8-8741-c3582d6df4ec.jpg)
![img-20181207-wa0009](https://user-images.githubusercontent.com/1778297/49673944-4063d180-fa3e-11e8-88d5-7e6b5ea5033e.jpg)
![img-20181207-wa0008](https://user-images.githubusercontent.com/1778297/49673945-4063d180-fa3e-11e8-9033-b4445e4a653e.jpg)

**Comment by hilyas** [comment]
I agree. It's important. The waqf helps preserve the meaning.

**Comment by tifa2UP** [comment]
+1. Want to look into it @bahaa96

**Comment by piraka9011** [comment]
Fixed in new front end
