### ISSUE TITLE
Mixing rtl and ltr content

### ISSUE THREAD

**Issue by hilyas** [Tarteel-io/tarteel.io#142]
Browsing the site, I noticed an issue with the Arabic version of the site which has some English text in it. Not sure if the intent is to mix both languages, but the ltr needs to be fixed. Example in the screenshot.
<img width="781" alt="screen shot 2018-12-07 at 10 23 23 pm" src="https://user-images.githubusercontent.com/727228/49681405-20003b00-fa6f-11e8-96eb-35e6d0e4610f.png">

**Comment by tifa2UP** [comment]
Thanks for bringing it up @hilyas! 

@abidlabs @bahaa96 are Ali's changes implemented yet?

**Comment by piraka9011** [comment]
This appears to be fixed in Bahaa's recent PR #152.
