### ISSUE TITLE
Quranic script for narrations other than Hafs.

### ISSUE THREAD

**Issue by hilyas** [Tarteel-io/tarteel.io#145]
Warsh is an option in the demographic data collection step, but the 'rasm' (Arabic text of the Quran) does not conform to the narration of Warsh. Maybe the app should emphasize the fact that it's Hafs only to keep things simple, or implement a choice of narration before starting the audio data collection. 
<img width="190" alt="screen shot 2018-12-07 at 10 46 27 pm" src="https://user-images.githubusercontent.com/727228/49681593-a23e2e80-fa72-11e8-8614-9131eaccc0c7.png">

**Comment by mmayet** [comment]
Agreed. I think we mentioned sticking to just Ḥafṣ during the tajwīd
meeting.

**Comment by piraka9011** [comment]
While the tajweed was meant to be hafs only, I think we still have the opportunity to collect the Warsh recitations even if we don't have the text (yet). 

It is my understanding that those who read warsh, and other qiraat are aware of the differences and can make a conscious effort to  recite according to their reading form. I think we should keep this as it is and if we find a parsable warsh text format, then we can display as needed.

**Comment by hilyas** [comment]
In my opinion, it will confuse the user. I know for a fact that some only know Warsh for example and cannot read Hafs. And some read Hafs thinking they're reading Warsh, and vice versa. My point is that not everybody knows where (and what) the differences are. Some wouldn't even know that there is more than one narration.
Differences are not only in photenic rules (tajweed), but also in word placement, word replacement, word omission, verse numbering, etc. It gets more complicated if we're dealing with other narrations as well.
To avoid confusion I think it should focus on Hafs, as it is widely used and everybody is familiar with it, and include more narrations in future releases.
If the goal is to collect all styles of narrations right now, it should be made clear to the user that the text presented is for Hafs.

**Comment by piraka9011** [comment]
Ok, JAK for taking the time to explain it. I'll include this in my next PR iA since it's an easy fix.

**Comment by hilyas** [comment]
Jazak Allah khayran. I appreciate the flexibility!
