### ISSUE TITLE
Gitflow model

### ISSUE THREAD

**Issue by hilyas** [Tarteel-io/tarteel.io#147]
What do you guys think of using gitflow. Basically merging feature/fix/etc.. branches into a Develop branch and keeping Master for releases.
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by piraka9011** [comment]
Salam Ilyas,

I believe we are using this model (technically, see our branches and forks). Contributors create a fork/branch for a specific feature they implement, a PR is generated and reviewed. Changes are pushed to develop for staging and master for production. 

While we don't have any official releases yet, it would be good practice to label them (currently they are just milestones). We have some major changes coming for the app version of this so it would be good to use release versions.

Check out our `CONTRIBUTING.md`. PM me and I can point you to features you can contribute to and how to get started.
