### ISSUE TITLE
Release for recitation data?

### ISSUE THREAD

**Issue by tarekeldeeb** [Tarteel-io/tarteel.io#155]
Salam,
[Reopening #105]

I'm developing a Quran Speech model already, using a fork from mozilla and data sets from http://quran.ksu.edu.sa/ayat

Project is hosted at
https://github.com/tarekeldeeb/DeepSpeech-Quran

I need to give a try using the current tarteel data set. Can you release the dataset? Tarteel had reached 10K+ already .. Ma Shaa Allah.

Jazakom Allah Khairan,

**Comment by khanh111** [comment]
Assalam Alaikum @tarekeldeeb,
Instructions for downloading our current data are at tarteel.io/download-audio. Please note that almost nothing is labeled yet (evaluation is being rolled out soon) and that the download will literally give you everything we have so far (so downloading an hour later will have more recordings than now).

We are continuing to work on data cleaning, labeling, and evaluation going forward Inshallah. Please feel free to reach out if you have any other issues.

Jazakallahkhair for reaching out,
Hamzah
