### ISSUE TITLE
"thank you for evaluating" keeps showing up after every 5 evals

### ISSUE THREAD

**Issue by mmayet** [Tarteel-io/tarteel.io#172]
slows down a long eval session.
make it like the main page - 5 verses to start
but after that, it's just unending

**Comment by piraka9011** [comment]
@bahaa96 @tifa2UP feature to add in the new front end?

**Comment by abidlabs** [comment]
On a related note, can we have the next audio files autoplay as soon as you click the thumbs up or thumbs down? For long evaluation sessions, it would save effort :)

**Comment by tifa2UP** [comment]
Added to the new frontend: 

1) Ayas play automatically
2) Popup is removed
