### ISSUE TITLE
have evaluator for men & women option

### ISSUE THREAD

**Issue by mmayet** [Tarteel-io/tarteel.io#174]
a looooooooooot of sisters' biggest concern for not wanting to use tarteel is men being able to hear. Can we add a toggle option to only hear men or only hear women?

we can't complain about low female usage if we don't respect their privacy

**Comment by abidlabs** [comment]
Thanks for the suggestion @mmayet. We'll be taking a few steps to protect gender-based privacy, as spelled out in #179. Closing this, because it is subsumed by #179.
