### ISSUE TITLE
Ibrāhīm shows up very weird in chrome Android - إِبْرَٰهِۦمُ 

### ISSUE THREAD

**Issue by mmayet** [Tarteel-io/tarteel.io#177]
إِبْرَٰهِۦمُ
إِبْرَٰهِـٖمُ

In the script or the Qurʾān, it's not written as - إِبْرَاهِيم - so there's no alif or yaa
Not sure how to remedy this. But it looks confusing.

**Comment by piraka9011** [comment]
Do you have a specific ayah example? or is this in general.

**Comment by piraka9011** [comment]
This apparently is fixed in the new front end. Tested on my Android (chrome and mozilla) and desktop.
