### ISSUE TITLE
Minimum Age 13?

### ISSUE THREAD

**Issue by nightblade9** [Tarteel-io/tarteel.io#181]
I asked a 10-year-old (after getting consent from their parent) to record five ayaat. On the demographics page, the minimum age listed is 13-18.

Can you provide an option for ages under 13? Or, did you purposely want data from 13yo+ only?

**Comment by abidlabs** [comment]
Salaam, yes we are only looking to collect data from folks at least 13 years or older, in order to protect children's privacy.

**Comment by nightblade9** [comment]
Wa'alikum as-salaam. How would I go about deleting their submissions, then?

**Comment by abidlabs** [comment]
Can you send us (contacttarteel@gmail.com) the session_id associated with the recording? You can find this by visiting the "My Profile" page and looking at the URL. It should be something like https://www.tarteel.io/profile/SESSION_ID
