### ISSUE TITLE
round sukūn not showing up right (3:144) - أَفَإِي۟ن

### ISSUE THREAD

**Issue by mmayet** [Tarteel-io/tarteel.io#183]
![round sukun](https://user-images.githubusercontent.com/6694374/51634097-3cb1de80-1f08-11e9-987c-d8a3ffb68b55.png)

it uses this character ْ
but shows the large section delineator.

**Comment by tifa2UP** [comment]
This is fixed in the new frontend. Thanks @mmayet!
