### ISSUE TITLE
Audio evaluation by automatic and human-reviewed annotations

### ISSUE THREAD

**Issue by abidlabs** [Tarteel-io/tarteel.io#33]
A lot of people will submit blank recordings as they learn to use the system. Can we automatically learn to exclude these in the ayah count and the bias for the random picker?

**Comment by piraka9011** [comment]
External tables:
- One for automated annotations
- One for manual annotations
One Manual for Tajweed, One Manual for Hifz, One Auto for Hifz

A new Django model is needed for Manual Tajweed.

Info for Tajweed:
- Letter
- Degree
- Category
- Session ID for evaluator
- Unique ID
- Letter: both position and character
- ID of corresponding recording

Soft suggestions based on deterministic rules.

**Comment by piraka9011** [comment]
Need to consider i18n when providing categories. (madd -> prolongation, tafkheem -> Fattening). Maybe just keep them in Arabic? :sweat_smile:

**Comment by abidlabs** [comment]
Great, for the Manual Hifz annotations, here's the functionality I have in mind:

1. The ability for a user to listen to a batch of recordings (maybe 5-10?) that have been uploaded, and see the correct text next to it.
2. The user should have a way of saying whether this is the correct verse being recited.
3. Once the user has evaluated all of the verses, they should be able to submit it and we record the evaluation data, as well as which user has submitted the evaluations (perhaps based on the session).
4. Finally, it would be nice if once the user has submitted evaluations, they could see a message with the total number of verses they have evaluated, and have the option to continue evaluating the next batch of verses.

**Comment by piraka9011** [comment]
So I've got the following up and running for the tajweed evaluation. Evaluator sees highlighted words and rule to check for and selects y/n for evaluation. If user hits no, a small radio div pop ups to indicate the degree of the mistake. 

Extra feature I can finish is to have this page accessible only via login.
![tajweed](https://user-images.githubusercontent.com/16828657/49697513-71bcd880-fbc9-11e8-9144-d5601ff6b11b.png)
