### ISSUE TITLE
Sometimes the ayah image doesn't show up

### ISSUE THREAD

**Issue by abidlabs** [Tarteel-io/tarteel.io#72]
I've heard from several people that the ayah image didn't show up. They had to click "next ayah" and then "previous ayah" for the image to show up.

**Comment by bahaa96** [comment]
I'll try to reproduce this issue some how but I guess It's not easy to get reproduced

**Comment by abidlabs** [comment]
Yes that was my impression as well. And the issue only seems to happen once -- once you click on "next ayah" and "previous ayah", it goes away completely.

**Comment by abidlabs** [comment]
I'm closing this as it should be solved by #83 which is being worked on by @mohamedgomran
