### ISSUE TITLE
Have a page that shows demographic breakdown

### ISSUE THREAD

**Issue by abidlabs** [Tarteel-io/tarteel.io#75]
- Users/ayahs
- Gender, race, age, qira'ah

**Comment by abidlabs** [comment]
@aliabid94 Can you make a new public-facing page "/demographics" and plot these demographics from the DB? Another good thing would be distributions of # recordings / ayah (e.g. how many ayahs have 0 recordings, how many have 1, etc.)

**Comment by aliabd** [comment]
I'd really like to help with this

**Comment by abidlabs** [comment]
Sounds good. My suggestion is that we can have a public-facing demographics breakdown that replaces the demographics form when the user has already filled out the demographics form.
