### ISSUE TITLE
Ayah Images / non-Uthmani Fonts 

### ISSUE THREAD

**Issue by abidlabs** [Tarteel-io/tarteel.io#83]
Right now, we're using images for all of the ayahs, that creates issues on mobile when the width of the ayah is very long. The better option would be to have use a nice font. If we go down this route, we should also support the desi-style font, as I've heard from a couple of desis that they're finding it hard to read this style.

**Comment by mohamedgomran** [comment]
@abidlabs It would be more efficient to display it as a text with me_quran, Scheherazade, KacstQurn, or KFGQPC Uthman font.

I can do it and make a pull request, what do you think?

**Comment by abidlabs** [comment]
Thank you @mohamedgomran for pointing this out. I think this is a great suggestion. Having the ayah text would allow us to:
* load the ayaat text faster
* allow us to adjust font sizes to get more readable text on mobile devices

Please go ahead and take this issue, jazakallahu khair. A few things that come to mind:
* I personally find the me_quran font the easiest to read.
* It is crucial to make sure that the ayah text is exactly correct for every verse. You may consider the Tanzil project (http://tanzil.net/download) for the text.

**Comment by mohamedgomran** [comment]
@abidlabs Sorry for being late, I'm on a vacation for a few days. I will start working on it with a friend tomorrow and I hope to deliver it in same day in shaa Allah.

**Comment by abidlabs** [comment]
Thank you @mohamedgomran, I went ahead and merged your PR. I made a few changes to the data file that it was reading from, but otherwise, I pretty much pulled your code directly.
