### ISSUE TITLE
Ayah Image not loading

### ISSUE THREAD

**Issue by tifa2UP** [Tarteel-io/tarteel.io#89]
Not sure if this is a duplicate, but as I was reading Surat Alkahf ayah 47 I got an empty screen. This happened after going through 47 ayas.

P.S. Was fixed after refreshing the page. Not sure if this has to do with API limits @abidlabs 

![image](https://user-images.githubusercontent.com/11590314/44941754-ce059600-ad58-11e8-851c-c60041ece0fc.png)

**Comment by tifa2UP** [comment]
Update: it looks like it just much takes more time to load.

P.S. I've overserved this continuous recitation mode. Not the regular one

**Comment by bahaa96** [comment]
Is This issue still exists ? Someone has committed a preload for the images.

**Comment by tifa2UP** [comment]
I'll check it. feel free to close for now

**Comment by mohamedgomran** [comment]
@tifa2UP  I think replacing images with text will be more efficient and would eliminate this issue #83, waiting for a response to start working on it.

**Comment by tifa2UP** [comment]
@mohamedgomran will update you soon iA!

**Comment by abidlabs** [comment]
I'm closing this as it should be solved by #83 which is being worked on by @mohamedgomran

**Comment by MohamedAliRashad** [comment]
This issue needs to be reopened because it still hasn't been fixed at least for me ....

**Comment by bahaa96** [comment]
Brother, We're no longer using images we are just using new fonts it's just heavy we are working on optimizing these fonts to load faster.

**Comment by tifa2UP** [comment]
@MohamedAliRashad that occurred because our API was down. Should be working as expected now. Feel free to reopen the ticket if you're still experiencing it

**Comment by MohamedAliRashad** [comment]
@tifa2UP it's up and running .... thanks :-)
